// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdralfmfkwenzqowtsoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkcmFsZm1ma3dlbnpxb3d0c295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDkyNzUsImV4cCI6MjA2MjcyNTI3NX0.300JgqMPRwBOEwIRFVF9jbWuAGvYkvr22a2eIAFIDAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);